Connect to an address directly
adafruit/Adafruit_CircuitPython_BLE pull request #135
Opened 2021-09-10 19:07 UTC by tannewt

This is helpful for reconnecting to a device we had already
connected to. The `connect()` call will do its own scan when
connecting.

2021-09-10 19:15 UTC, dhalbert requested changes
Looks good! Just one doc change.

We could just omit the union type, or use some typical sphinx notation.
https://stackoverflow.com/questions/34647966/how-to-express-multiple-types-for-a-single-parameter-or-a-return-value-in-docstr

2021-09-10 19:15 UTC, dhalbert commented on adafruit_ble/__init__.py
> +        :param Advertisement peer: An `Advertisement`, a subclass of `Advertisement` or `Address`
```suggestion
        :param peer: An `Advertisement`, a subclass of `Advertisement` or `Address`
```
or
```suggestion
        :param Advertisement/Address peer: An `Advertisement`, a subclass of `Advertisement` or `Address`
```

2021-09-10 20:07 UTC, dhalbert commented
@tannewt Did you see my suggestion above about the type of the arg, which now is only `Advertisement`? I do see you fixed the errors.

2021-09-13 17:53 UTC, dhalbert approved these changes

2021-09-13 17:53 UTC, merged

2021-09-13 19:06 UTC, tannewt commented
(I hadn't seen your comment.)